vich_uploader:
  db_driver: orm  # Set to 'orm' if using Doctrine ORM
  mappings:
    livre_images:
      uri_prefix: /uploads/livres
      upload_destination: '%kernel.project_dir%/public/uploads/livres'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    categories_images:
      uri_prefix: /uploads/categories
      upload_destination: '%kernel.project_dir%/public/uploads/categories'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
